### ISSUE TITLE
`tokenize.py` should be `tokenize.sh`?

### ISSUE THREAD

**Issue by SeitaroShinagawa** [tktkbohshi/FairseqTutorial#2]
Thanks for sharing your tutorial.  

I found `tokenize.py` cannot be downloaded using `data_download.sh`.  
https://github.com/tktkbohshi/FairseqTutorial/blob/main/work_dialog/data_download.sh#L8  

I think `tokenize.py` should be `tokenize.sh`. Could you check it? Thanks.

**Comment by tktkbohshi** [comment]
Sorry for a late correspondence.
I have fixed it.
Thank you.
